title: The Investigative Dashboard
email: id@occrp.org
description: >-
  Investigative Dashboard (ID) is intended to help investigative journalists to
  do their work in a fast and effective way. It combines a number of software
  tools, including search engines, databases, a research support system and a
  file manager, to try to shorten the lead time from story inception to
  publication.
baseurl: ''
url: ''
logo: https://cdn.occrp.org/common/favicon/large.png
google_analytics: ''

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
